### ISSUE TITLE
ValueError: a must be non-empty

### ISSUE THREAD

**Issue by louielu1027** [hizhangp/triplet#6]
Epoch 1
Shuffling the data ...
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    sw = SolverWrapper(solver, output_dir, pretrained_model, gpu_id, data)
  File "train.py", line 32, in **init**
    self.solver.net.layers[0].set_data(data)
  File "/home/dl1/lvlu/triplet-master/triplet/data_layer.py", line 77, in set_data
    self._shuffle_data()
  File "/home/dl1/lvlu/triplet-master/triplet/data_layer.py", line 22, in _shuffle_data
    np.random.choice(self._data._sample_person[person]))
  File "mtrand.pyx", line 1080, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:10392)
ValueError: a must be non-empty

**Comment by hizhangp** [comment]
@louielu1027 It seems that the code you ran is an old version, it lacks the statements to delete `self._data._sample_person[person]` when it's empty.

**Comment by iamZe** [comment]
@hizhangp 用新版的还是有相同的错误

**Comment by peternara** [comment]
@hizhangp @iamZe  i hava a same problem. Do you solve this problem?
