### ISSUE TITLE
AttributeError: 'DataLayer' object has no attribute '_data'

### ISSUE THREAD

**Issue by wenfahu** [hizhangp/triplet#7]
I am using the triplet loss with my inception batch-norm network. And it breaks down on the 1st iteration.

```
Epoch 1
Shuffling the data ...
Solving...
I1216 21:59:13.990463  6601 solver.cpp:337] Iteration 0, Testing net (#0)
Traceback (most recent call last):
  File "triplet_train.py", line 97, in <module>
    sw.train_model(max_iters)
  File "triplet_train.py", line 59, in train_model
    self.solver.step(1)
  File "/home/wenfahu/inception_bn_face/triplet/data_layer.py", line 107, in forward
    blobs = self._get_next_minibatch()
  File "/home/wenfahu/inception_bn_face/triplet/data_layer.py", line 37, in _get_next_minibatch
    if self._index + self.batch_size <= len(self._data._sample):
AttributeError: 'DataLayer' object has no attribute '_data'
```

**Comment by hizhangp** [comment]
@wenfahu It seems that you forget to call `self.solver.net.layers[0].set_data(data)` in `train.py` before iteration.

**Comment by wangpichao** [comment]
What's the results you obtained using your implementation?

**Comment by wangpichao** [comment]
Could you share the pretrained caffemodel?
